### ISSUE TITLE
Jumpy icons in Internet Explorer

### ISSUE THREAD

**Issue by petropages** [9bitStudios/flexisel#46]
We are using the flexisel script on this site:
http://mccorp.com/

It is great in all browsers, IE, as is the case with most things. The icons though, they seem to jump a bit from side to side as they are scrolling. Any ideas on a possible fix?

**Comment by 9bitStudios** [comment]
Hi there petropages -- I see what you are referring to. I am not entirely sure at present what the fix might be. I see that you have modified the slider to kind of have a continuous scroll effect (which is a bit different from how the carousel was originally designed). It's likely due to the continual math being done on the items in the carousel when there is no interval between transitions.

**Comment by petropages** [comment]
I appreciate you taking a look at it. In the future, if you run across a more elegant solution than we are using I look forward to trying it. It is a cool little piece of script and again, I appreciate the reply and attention to your product.
