### ISSUE TITLE
Audio stops  as slide goes out of visibility area

### ISSUE THREAD

**Issue by ssameer07** [9bitStudios/flexisel#56]
Hello ,
first of all great work guys...

The slider works great...recently as tried to add an audio in one of the slides , obviously the  audio plays...BUT when the that slide goes behind the audio stops...

I'm simply using the audio tag  as
<pre><code>
&lt;li&gt;
 &lt;audio id="audio1"&gt;
     &lt; source src="http://www.maninblack.org/demos/Bring%20It%20Down%20demo.mp3"&gt;    &lt;/source&gt;
 &lt;/audio&gt;
&lt;/li&gt;</pre></code>

and within the script 
<pre><code>
 var audio = document.getElementById("audio1");
    audio.load();
    audio.controls = true; 
</pre></code>

I have autoplay = true defined....
what do I need to do to make the audio play continuously when user hits the play button from controls....

OR

I tried the onClick event over li to set auto-play false but it also didn't work.
Can I simply on have click over that particular "li" tag play the audio and set auto-play to false and again clicking over same li pause the audio and reset auto-Play to true???

**Comment by 9bitStudios** [comment]
Hi there -- I will try to take a look at this when I get a chance. I am presently on holiday so it may not be until I get back.

**Comment by 9bitStudios** [comment]
I know it has been awhile since this issue was opened but I did a bit of research on it and from what I have read this is apparently the standard functionality for browsers to implement. It prevents sites from playing sound that is unable to be turned off by controls that are not visible within the current viewport/page (which was one of the scourges of the web in the days of Flash-heavy sites). Anecdotally, I see this behavior in my Twitter timeline where if I start a video and then scroll down, the video and accompanying sound will stop.

I'm not 100% sure that what I have come across is 100% accurate and I'm too lazy to go dig up the actual spec, but seeing as this isn't really an officially supported element to this plugin, I'm going to close this issue out for now.
