### ISSUE TITLE
When autoplay is enabled, DOM gets bombarded with duplicate clones.

### ISSUE THREAD

**Issue by umesh53** [9bitStudios/flexisel#77]
When autoplay is enabled for infinte loop, looped elements ("LI ") gets cloned and cloned without any end point. This is a major concern I guess. We can do that by modifying the code. I tried and did customize the same.

Changes::
From::

```
if(settings.infinite) {    
      var childSet = object.children();
      var cloneContentBefore = childSet.clone();
      var cloneContentAfter = childSet.clone();
      object.prepend(cloneContentBefore);
      object.append(cloneContentAfter);
}
```

To::
```
if(settings.infinite) {
      var childSet = object.children();
      var cloneContentBefore = childSet.clone();
      var cloneContentAfter = childSet.clone();
      cloneContentAfter.remove();
      object.append(childSet);
}
```

The above doesn't clone every time but only clones twice which can reduce a lot of burden. I'm also trying to mitigate it to one.

**Comment by 9bitStudios** [comment]
Hi there umesh53. I'm afraid I am not entirely understanding where this issue is coming from. If you look at the demo http://9bitstudios.github.io/flexisel/ the autoplay is enabled on the last carousel and if you inspect the HTML the list items there are not infinite in number. The cloning happens inside of a method that is only called once when the plugin is initialized. 

Do you have a demo link available where you can show where/how this is happening? If so, please also let me know which browser are you using?

**Comment by umesh53** [comment]
Aah.. Sorry. It is not replicating "**n**" times but thrice. May I ask why is that? Even in the [http://9bitstudios.github.io/flexisel/](url) demo, it is getting duplicated thrice. Why is that important? Can't it done without replicating elements? As I have mentioned before, I removed cloning and it is working fine for me.

**Comment by 9bitStudios** [comment]
It essentially comes down to the approach I have taken for this particular plugin in its "infinite" carousel feature. 1 cloned set is placed before the original set and 1 cloned set placed after this... with the original set sitting in the middle (visible) so that on initialization you'd still be able scroll left (reverse) and still see all the items without any blank spaces not yet populated. The 1 set before, the 1 set after, and the 1 original/visible set makes the 3X that you are seeing.
